### ISSUE TITLE
Rails 5 compatibility?

### ISSUE THREAD

**Issue by maia** [afair/postgresql_cursor#21]
Does postgresql_cursor work with current Rails 5 pre-releases or is it better to expect that this gem will not be compatible with Rails 5 and will need major reworking? As the last commit was 14 months ago, have people moved on to alternative solutions, and if yes, which?

**Comment by afair** [comment]
My preliminary tests have shown postgresql_cursor does work with Rails 5, much to my surprise! Since this depends on private ActiveRecord API's, it can easily break between Rails releases, even between now and the final release of Rails 5.

My plan is to wait until rails 5.0.0.rc1 and do a full test against it, and release a new version with the last minor fixes. I still use this gem in my daily work, and have no plans to abandon it; it has been feature complete for a while so doesn't need much work outside of tracking new Rails releases.

I am not aware of current, alternate solutions, but the core of the gem is actually rather small and anyone can extract it into their own apps if something unforeseeable happens in the future.

**Comment by maia** [comment]
@afair , thanks for the information, that's surprising indeed and great to hear!

PS: I partly assumed it was abandoned as there are a few forks with more recent activity and two stale pull requests.
