### ISSUE TITLE
Cannot "includes" other records when using this

### ISSUE THREAD

**Issue by QuotableWater7** [afair/postgresql_cursor#25]
I'm not sure how difficult it would be to do, but I realized `Model.includes(:something).each_instance` will return back records that do not have the associations preloaded.

**Comment by afair** [comment]
This may be difficult, but it certainly would be nice to do. This library mostly performs the row fetching and returns each row as either a Hash or Model.instantiate(). It does this outside of ActiveRecord internals that work to map the database results back into Objects (like what an ORM does). I think it would be easier to introduce Cursors into ActiveRecord than do this :-)

I'll leave this open in case some aspiring coder can put together a Pull Request, or if I have any ideas in the future.

**Comment by lvonk** [comment]
Hi,

I created a simpler cursor (less features that is...) inspired by this cursor that supports the includes and works for our use case.

I found that ActiveRecord used the `ActiveRecord::Associations::Preloader` to make `includes` work. See the [exec_queries](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation.rb#L680) method in `ActiveRecord::Relation`. The `preload` takes an array of records and an array of assocications. So in order to make it work the `fetch` method will to return an array instead of a single row. When doing so each time a block in fetched it will do the preloading of the associations.

This cursor is then used as follows: 
```ruby
Cursor.new(Model.includes(foos: [:bar], :bar_foos).where(id < 10000000).order(:id)).find_each do |model|
  # do something
end
```

The entire cursor code is here: https://gist.github.com/lvonk/9fefe788616a22170bf53fadd7bcb66a

Will this work in this gem you think? If so I could try to create a PR for this...
