### ISSUE TITLE
Why is FOR UPDATE not supported?

### ISSUE THREAD

**Issue by FooBarWidget** [afair/postgresql_cursor#30]
The README says that this gem is not intended to support FOR UPDATE to process and update each row in place. But why not? I scanned the functionality of this gem and the PostgreSQL documentation for a bit but it's not obvious why FOR UPDATE is not supported.

**Comment by afair** [comment]
Hongli,

The purpose of this gem was to be a better "find_in_batches" for very large result sets, with complex queries and sort. I have done nothing to prevent the "FOR UPDATE", have not added direct support for it either, nor have I tested to see if that would work. 

I just tried something and it looks like it could work as follows:
```
Widget.all.each_instance_by_sql("select * from widgets for update") do |widget|
  widget.update(...)
end
```

The library has no AREL-enhancements to append "FOR UPDATE" to the SQL string (each_instance_for_update). Also [FOR UPDATE](https://www.postgresql.org/docs/9.5/static/sql-select.html) has limitations on where it can be used.

Postgres should lock all the rows being returned during the operation, preventing other concurrent updates. Because this library returns batches of 1000 rows at a time, I don't know if it locks just the rows returned from the last FETCH, or the entire result set.

**Comment by FooBarWidget** [comment]
I've just tested on PostgreSQL 5.4. PostgreSQL only locks the rows returned from the last FETCH.

It doesn't look like your library needs any special support for FOR UPDATE. The standard AREL `lock` method works fine for me:

~~~ruby
Product.lock.each_row { ... }
# declare cursor_defecb2fcec146bd84dce3da427e8be0 cursor for SELECT "products".* FROM "products" FOR UPDATE
# fetch 10 from cursor_defecb2fcec146bd84dce3da427e8be0
~~~

**Comment by afair** [comment]
Excellent! I didn't know about the `lock` method.

I'll update the README with these findings. Thanks for checking that out, and all the other products you make that helps me!

**Comment by FooBarWidget** [comment]
Thanks for updating the documentation! The documentation as a whole is excellent. :)
